# Generated by Django 3.0.7 on 2020-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserActivity', '0002_activityperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
